version: '3.8'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: always

  bot:
    build: .
    command: ["node", "bot.js"]
    depends_on:
      - server
    restart: always
