name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Ensure this matches your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gitfolio:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gitfolio:latest

      - name: Stop Previous Deployment
        run: |
          curl -X DELETE "https://app.koyeb.com/v1/services/${{ secrets.KOYEB_SERVICE_ID }}/instances" \
            -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}"

      - name: Deploy to Koyeb
        run: |
          curl -X POST "https://app.koyeb.com/v1/services/${{ secrets.KOYEB_SERVICE_ID }}/redeploy" \
            -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}"
